### ISSUE TITLE
Mplayer OSX randomly aborts playback

### ISSUE THREAD

**Issue by apathyash** [sttz/MPlayer-OSX-Extended#103]
I'm using the program to screenshot from mkv files. in the middle of screenshotting, the program will shut down and I get the notification "Playback Error. Abnormal playback termination. check log file for more information." I've tried deleting and reinstalling, but it keeps happening. Mac OS high sierra. Any help?

**Comment by joonaskokko** [comment]
Having the same problem. No log information anywhere.

**Comment by noyannus** [comment]
Same here. (Rev. 16, macOS 10.13.6 (17G65). 
No log, only information is that available in the error dialog.
![screenshot 2018-08-25 um 20 38 54](https://user-images.githubusercontent.com/6339921/44713251-0d12bd80-aab3-11e8-9891-695f7a375b22.png)
After restarting with the non-default player, no further crashing observed. So 1x/movie there is the crash-restart interruption (but I have not checked if that was with _every_ movie).

Also, of the two options for "Open with binary", only the "Official MPlayer SVN" is available in Preferences. Please allow to select the other one as standard binary. That could be a workaround until the Official binary is fixed.

**Comment by Heike779** [comment]
I do have exactly the same problem on High Sierra 10.13.6 . 
I used MPlayer OSX Extended for years with Snow Leopard 10.6.8 without any problems but since I upgraded to High Sierra 10.13.6 EVERY movie I watch gets interrupted by abnormal playback termination (mp4 and mkv with various resolutions).
It drives me crazy.
Please, please fix this! I love and need my MPlayer OSX Extended. I'd pay for it.

**Comment by VivaLosDoyers** [comment]
This problem exists in Mojave as well :(

**Comment by ajeansres** [comment]
Since upgrading to Mojave, this has been a constant issue. With nearly every video I watch, grab screencaps from, it aborts the program. Before Mojave, I was using MacOS Sierra and had ZERO issues with playback unless I had to force quit due to an unrelated problem. Please fix this soon. None of the other programs I've used in the past comes close in comparison to this one, and I would love to continue using it, but might be forced to find another if this keeps up.

**Comment by saniv** [comment]
Same here. OSX Mplayer crashes like crazy, no matter the file type played. OGG, MP3, WAV - all crashes it.
