### ISSUE TITLE
CoreServicesUI crash on launch of MPlayer

### ISSUE THREAD

**Issue by 4chanmoot** [sttz/MPlayer-OSX-Extended#78]
I just installed rev16-test1, and I'm getting a crash on launch. If I launch from /Applications, CoreServiceUI crashes. 

When launching from the command line, I see: 
`
| => /Applications/MPlayer\ OSX\ Extended.app/Contents/MacOS/MPlayer\ OSX\ Extended 
2015-12-04 15:55:43.280 MPlayer OSX Extended[83179:18530040] Failed to connect (fcControlWindow) outlet from (VideoOpenGLView) to (FullscreenControls): missing setter or instance variable
`

**Comment by sttz** [comment]
Thanks for reporting! Seems like XProtect is caught in an infinite loop when checking the bundle's libraries.

For now, you can manually remove the quarantine bit using `xattr -d com.apple.quarantine [path_to_app]` to bypass the check while I figure out why it's happening.

Users updating in-app via Sparkle should not be affected as the app is not quarantined that way.

Also note there's an issue with the Fontconfig dialog, so MPE just seems to hang when actually Fontconfig is updating its font cache.

**Comment by sttz** [comment]
Oh, the infinite loop was caused by a circular dependency. HarfBuzz did already depend on FreeType but now FreeType has also introduced a dependency on HarfBuzz.

For now I disabled FreeType's HarfBuzz support and uploaded a new build, which no longer crashed XProtect for me. I did have to reboot since something broke after XProtect crashed and it would tell me the app was damaged.
