### ISSUE TITLE
Playback cursor does not appear in OS X El Capitan

### ISSUE THREAD

**Issue by AA16** [sttz/MPlayer-OSX-Extended#81]
Please someone helps me here. It seems that the solution to the disappearance of the playback cursor has already been solved in this website. But, I'm still having a problem with it. I'm not that expert in this kind of work. There is the link of the solution: https://github.com/sttz/MPlayer-OSX-Extended/commit/c11dedf7965b2527df5121c1b4c0c973fd0a5246

I tried to find the file ''source/interface/player/ScrubbingBar.m'', but I could not locate it. The only folders shown in the MPlayer-OSX-Extended app are: Resources, _CodeSignature, Frameworks, and MacOS. I tried to search for the file ScrubbingBar, but no luck. 

Thank you in advance!

**Comment by meonlol** [comment]
I wanted to confirm this, but then I saw that the fix was tagged `rev16-test1`. I've just installed a new version (via homebrew) and it is currently at rev15. So we'll have to wait for revision 16 to be released before this is fixed, or build it from source.

Incidentally, the file you where looking for is a source-code file and can not be found in a regular installation. The way all this works is that programmers write the source code files by hand (these here on github for example, written in objective-C), but for the computer to be able to run it we need the 1's and 0's it can understand. (I don't know why I've just started to explain the process of writing software, but I won't stop now) You then do what is called compiling, which first reads the source code (lexing), then tries to make sense of it (parsing), and than _rewrites_ it to a lower-level programming language ([assembly](https://en.wikipedia.org/wiki/Assembly_language)), optimising along the way. The end result of which can then be _translated_ to the 1's and 0's that the computer can understand. So for example `MOV AL, 61h` is assembly code, which translates directly to `10110000 01100001`, no analysing or optimising is done in this step. We usually call the end-result bytecode. The files you get with your installer are only the compiled bytecode files.

Man, I've put a lot of work into that. Hope you appreciate the lecture, that you didn't ask for, from a mature developer with a whopping 2 years of experience haha.
