### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by forthrin** [sttz/MPlayer-OSX-Extended#91]
I wanted to try an alternative to VLC, and gave this program a spin. There were a few good things, but quite a lot of issues. I'm posting my experiences here to check if these are likely to be addressed.

Good things (compared to VLC)
- Much more resilient when playing incomplete video files
- Almost instant skipping forwards/backwards
- Better fast-forward keys (single cursor key)

General problems
- Doesn't smooth-scale video when upscaling / full screen (worst problem!)
- Doesn't play x265
- Doesn't offer to associate common video types with the program
- Doesn't offer way to bypass occasional 5 minutes "Building font cache" hell
- Crashes occasionally and suddenly for no reason

Subtitles
- Subtitles are quite ugly in general (thick border, transparent, etc.)
- UTF-8 subtitles are displayed incorrectly by default
- Subtitle filenames with country code (eg. "Movie.fr.srt") are not loaded

Keyboard
- Esc in full screen should escape full screen like other players, not quit the application!
- User should get visual feedback on volume adjust (especially at 100%)
- Volume adjust should be fairly logical keys like + and -
- Square brackets and curly braces don't work for non-US keyboards (avoid them!)
- Mac media keys (F7-F12) don't work

Mouse
- Mouse pointer disappears over the video window
- Should be possible to disable mouse wheel (unwanted action happens so easy!)

UI
- Consider merging full screen UI with window UI (ask me for details)
- Consider switching UI to flat design

Name
- "MPlayer OS X Extended" doesn't exactly encourage word of mouth to friends.
- It's "macOS" now (but the OS name doesn't need to be in the program name)
- How about "MPX" or something else that rolls easily off the tongue?

**Comment by sttz** [comment]
Thanks for the feedback!

MPE is a really old codebase and there are many aspects of the application that have become old and outdated. Over the last years, I also haven't had much time to improve the situation, so the player has languished.

    Better fast-forward keys (single cursor key)

Not sure what you mean here? You can use the arrow keys and pg up/down to quickly skip through the video.

    Doesn't smooth-scale video when upscaling / full screen (worst problem!)

Should have been fixed in rev16-test1.

    Doesn't play x265

Supported as of rev16-test2.

    Doesn't offer way to bypass occasional 5 minutes "Building font cache" hell

There was no way around that, unfortunately, but Fontconfig was finally removed in rev16-test2, meaning no more rebuilding font caches.

    Crashes occasionally and suddenly for no reason

Please submit crash reports.

    Subtitles are quite ugly in general (thick border, transparent, etc.)

This is the way MPlayer renders subtitles (MPE is only a frontend). Maybe MPE can provide better defaults.

    UTF-8 subtitles are displayed incorrectly by default

Do you have an example subtitle file? Also try to set "Guess Encoding" to "Multibyte encodings only" in Preferences under Text.

    Subtitle filenames with country code (eg. "Movie.fr.srt") are not loaded

Better fuzzy matching has been on my TODOs. You can drag and drop subtitle files on a running movie to load them. You can also try adding "-sub-fuzziness 1" in Preferences under Advanced.

    Esc in full screen should escape full screen like other players, not quit the application!

That's not the case. Not sure what happened in your case, maybe the app crashed?

    Volume adjust should be fairly logical keys like + and -

MPE uses Command-Up/Down, just like VLC. QuickTime uses just Up/Down but those are used for seeking in MPE and I don't want to remove that.

    Square brackets and curly braces don't work for non-US keyboards (avoid them!)

MPE originally tried to imitate MPlayer's keybindings and there's definitely room to improve them.

    Mac media keys (F7-F12) don't work

Unfortunately, Apple doesn't provide an official API for those keys and the hacks that most applications use are pretty clunky.

    Mouse pointer disappears over the video window

Should be fixed in rev16-test1.

    "MPlayer OS X Extended" doesn't exactly encourage word of mouth to friends.
    It's "macOS" now (but the OS name doesn't need to be in the program name)
    How about "MPX" or something else that rolls easily off the tongue?

Yeah, as I said, it's an old project and not much updated in the last years. I'll consider a name change when the project is on better grounds again.

**Comment by forthrin** [comment]
Thanks for thorough feedback!

1. When will the releases you mention be available through Homebrew so I can test again?

2. Since you say this project is sort of stale, what other (lean!) frontends are there for MPlayer?

**Comment by sttz** [comment]
1. I'm not maintaining the Homebrew formula but I suspect they are waiting for a proper release, not a beta. Since it's been two years since the last beta I don't want to rush it and first wait for some feedback. But I'm trying to only include the necessary changes so that it won't take longer as needed.

2. I don't have a good overview of current players, I'm mostly just using MPE myself. As for MPlayer, development seems to have moved over to [mpv](https://mpv.io) and it has a simple GUI, although not very mac-like. I want to look into adding support for using mpv as a backend in MPE once the new version is released.

**Comment by valter1** [comment]
Hi, after updating the subtitle does not appear at all ?!?

**Comment by sttz** [comment]
@valter1 Please open a new issue with more details. What font do you have selected in preferences? Did you try different fonts / styles? If you press O a couple of times, does the time code get displayed or do you only see the play symbol? Also try to attach the log after trying to play a file with subtitles form `~/Library/Logs/MPlayerOSX.log`.

**Comment by valter1** [comment]
Thank you Adrian,
after I changed font and style, now is OK. 
I used Source Sans Semibold (not working), trying few others and finaly changed to Calibri Bold, working!!
And please, what about setting subtitle position, I want to set subtitle position little bit away from the bottom?

Best regards, Valter
