### ISSUE TITLE
rev16 (1610) on OSX High Sierra randomly aborting on 480p .mkv playback

### ISSUE THREAD

**Issue by TheButterZone** [sttz/MPlayer-OSX-Extended#93]
MPlayerOSX.log only goes from Jan 1-6.

**Comment by sttz** [comment]
Do you have an example file that you can share to reproduce the issue?

It seems that logging isn't working properly in rev16. You could try to play the file on the command line with the embedded mplayer binary to see if it's an issue with MPE or mplayer. The binary is located at

    /Applications/MPlayer OSX Extended.app/Contents/Resources/Binaries/mpextended.mpBinaries/Contents/MacOS/mplayer

**Comment by TheButterZone** [comment]
`/Applications/MPlayer\ OSX\ Extended.app/Contents/Resources/Binaries/mpextended.mpBinaries/Contents/MacOS/mplayer` ?

**Comment by TheButterZone** [comment]
```
New_Face failed. Maybe the font path is wrong.
Please supply the text font file (~/.mplayer/subfont.ttf).
subtitle font: load_sub_face failed.
New_Face failed. Maybe the font path is wrong.
Please supply the text font file (~/.mplayer/subfont.ttf).
subtitle font: load_sub_face failed.
```

~/.mplayer/ doesn't even exist when I go to folder.

**Comment by sttz** [comment]
MPE doesn't use Fontconfig anymore and you have to specify a font explicitly. Those are just the fallback paths where MPlayer looks for a font if it can't find one otherwise. Those messages are harmless and shouldn't lead to playback problems (apart from the OSD and subtitles not showing).

Were you able to play the MKV this way or did it abort playback as well?

**Comment by hvisage** [comment]
I've been seeing *random* crashes with MPlayerX, MPlayer-OSX_Extended on various files. restarting the files, doesn't have the failures either. Seems to have started with 10.13.3.
